import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/component/Navbar";
import Main from "@/component/Main";
import Offerings from "@/component/Offerings";
import Team from "@/component/Team";
import Blogs from "@/component/Blogs";
import Form from "@/component/Form";
import Footer from "@/component/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Main />
        <Offerings />
        <Team />
        <Blogs />
        <Form />
        <Footer />
      </main>
    </>
  );
}
